// <auto-generated />
using System;
using AgroMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroMarket.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgroMarket.Domain.Entities.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_hang_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("SanPhamDangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("san_pham_dang_id");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("Id")
                        .HasName("pk_chi_tiet_don_hang");

                    b.HasIndex("DonHangId")
                        .HasDatabaseName("ix_chi_tiet_don_hang_don_hang_id");

                    b.HasIndex("SanPhamDangId")
                        .HasDatabaseName("ix_chi_tiet_don_hang_san_pham_dang_id");

                    b.ToTable("chi_tiet_don_hang", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("longtext")
                        .HasColumnName("binh_luan");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_hang_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiBiDanhGiaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_bi_danh_gia_id");

                    b.Property<Guid>("NguoiDanhGiaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_danh_gia_id");

                    b.Property<int>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("so_sao");

                    b.HasKey("Id")
                        .HasName("pk_danh_gia");

                    b.HasIndex("DonHangId")
                        .HasDatabaseName("ix_danh_gia_don_hang_id");

                    b.HasIndex("NguoiBiDanhGiaId")
                        .HasDatabaseName("ix_danh_gia_nguoi_bi_danh_gia_id");

                    b.HasIndex("NguoiDanhGiaId")
                        .HasDatabaseName("ix_danh_gia_nguoi_danh_gia_id");

                    b.ToTable("danh_gia", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("loai");

                    b.Property<string>("MaGiaTri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_gia_tri");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_hien_thi");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.HasKey("Id")
                        .HasName("pk_danh_muc");

                    b.ToTable("danh_muc", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<bool>("IsDatHangTruoc")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dat_hang_truoc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiBanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_ban_id");

                    b.Property<Guid>("NguoiMuaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_mua_id");

                    b.Property<string>("PhuongThucNhanHang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phuong_thuc_nhan_hang");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_don_hang");

                    b.HasIndex("NguoiBanId")
                        .HasDatabaseName("ix_don_hang_nguoi_ban_id");

                    b.HasIndex("NguoiMuaId")
                        .HasDatabaseName("ix_don_hang_nguoi_mua_id");

                    b.ToTable("don_hang", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.HoaDonDienTu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_hang_id");

                    b.Property<string>("DuongDanPdf")
                        .HasColumnType("longtext")
                        .HasColumnName("duong_dan_pdf");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("longtext")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_xuat");

                    b.HasKey("Id")
                        .HasName("pk_hoa_don_dien_tu");

                    b.HasIndex("DonHangId")
                        .HasDatabaseName("ix_hoa_don_dien_tu_don_hang_id");

                    b.ToTable("hoa_don_dien_tu", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.HopDongBaoTieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DoanhNghiepId")
                        .HasColumnType("char(36)")
                        .HasColumnName("doanh_nghiep_id");

                    b.Property<decimal>("GiaChot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_chot");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTime>("NgayThuHoachDuKien")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_thu_hoach_du_kien");

                    b.Property<Guid>("NongDanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nong_dan_id");

                    b.Property<int>("SanLuongCamKet")
                        .HasColumnType("int")
                        .HasColumnName("san_luong_cam_ket");

                    b.Property<Guid>("SanPhamDangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("san_pham_dang_id");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_hop_dong_bao_tieu");

                    b.HasIndex("DoanhNghiepId")
                        .HasDatabaseName("ix_hop_dong_bao_tieu_doanh_nghiep_id");

                    b.HasIndex("NongDanId")
                        .HasDatabaseName("ix_hop_dong_bao_tieu_nong_dan_id");

                    b.HasIndex("SanPhamDangId")
                        .HasDatabaseName("ix_hop_dong_bao_tieu_san_pham_dang_id");

                    b.ToTable("hop_dong_bao_tieu", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.LichSuGiaoDich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_hang_id");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hanh_dong");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid?>("ThanhToanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("thanh_toan_id");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian");

                    b.Property<Guid?>("ThucHienBoiId")
                        .HasColumnType("char(36)")
                        .HasColumnName("thuc_hien_boi_id");

                    b.HasKey("Id")
                        .HasName("pk_lich_su_giao_dich");

                    b.HasIndex("DonHangId")
                        .HasDatabaseName("ix_lich_su_giao_dich_don_hang_id");

                    b.HasIndex("ThanhToanId")
                        .HasDatabaseName("ix_lich_su_giao_dich_thanh_toan_id");

                    b.HasIndex("ThucHienBoiId")
                        .HasDatabaseName("ix_lich_su_giao_dich_thuc_hien_boi_id");

                    b.ToTable("lich_su_giao_dich", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("anh_dai_dien_url");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<int>("DiemUyTin")
                        .HasColumnType("int")
                        .HasColumnName("diem_uy_tin");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ho_ten");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("kich_hoat");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mat_khau_hash");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.Property<decimal>("SoDu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_du");

                    b.Property<decimal>("SoDuChoXuLy")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_du_cho_xu_ly");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("ThongTinNganHang")
                        .HasColumnType("longtext")
                        .HasColumnName("thong_tin_ngan_hang");

                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("char(36)")
                        .HasColumnName("vai_tro_id");

                    b.HasKey("Id")
                        .HasName("pk_nguoi_dung");

                    b.HasIndex("VaiTroId")
                        .HasDatabaseName("ix_nguoi_dung_vai_tro_id");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.NhatKySanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hanh_dong");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiThucHienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_thuc_hien_id");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("char(36)")
                        .HasColumnName("san_pham_id");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian");

                    b.Property<string>("TxHash")
                        .HasColumnType("longtext")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_nhat_ky_san_pham");

                    b.HasIndex("NguoiThucHienId")
                        .HasDatabaseName("ix_nhat_ky_san_pham_nguoi_thuc_hien_id");

                    b.HasIndex("SanPhamId")
                        .HasDatabaseName("ix_nhat_ky_san_pham_san_pham_id");

                    b.ToTable("nhat_ky_san_pham", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.SanPhamChung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("cha_id");

                    b.Property<Guid?>("DanhMucId")
                        .HasColumnType("char(36)")
                        .HasColumnName("danh_muc_id");

                    b.Property<Guid>("DonViId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_vi_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_san_pham");

                    b.HasKey("Id")
                        .HasName("pk_san_pham_chung");

                    b.HasIndex("ChaId")
                        .HasDatabaseName("ix_san_pham_chung_cha_id");

                    b.HasIndex("DanhMucId")
                        .HasDatabaseName("ix_san_pham_chung_danh_muc_id");

                    b.HasIndex("DonViId")
                        .HasDatabaseName("ix_san_pham_chung_don_vi_id");

                    b.ToTable("san_pham_chung", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.SanPhamDang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChatLuongId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chat_luong_id");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta_chi_tiet");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiBanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_ban_id");

                    b.Property<Guid>("SanPhamChungId")
                        .HasColumnType("char(36)")
                        .HasColumnName("san_pham_chung_id");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("longtext")
                        .HasColumnName("ten_hien_thi");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_san_pham_dang");

                    b.HasIndex("ChatLuongId")
                        .HasDatabaseName("ix_san_pham_dang_chat_luong_id");

                    b.HasIndex("NguoiBanId")
                        .HasDatabaseName("ix_san_pham_dang_nguoi_ban_id");

                    b.HasIndex("SanPhamChungId")
                        .HasDatabaseName("ix_san_pham_dang_san_pham_chung_id");

                    b.ToTable("san_pham_dang", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)")
                        .HasColumnName("don_hang_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phuong_thuc");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_thanh_toan");

                    b.HasIndex("DonHangId")
                        .HasDatabaseName("ix_thanh_toan_don_hang_id");

                    b.ToTable("thanh_toan", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.TinNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiGuiId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_gui_id");

                    b.Property<Guid>("NguoiNhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_nhan_id");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("noi_dung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_tin_nhan");

                    b.HasIndex("NguoiGuiId")
                        .HasDatabaseName("ix_tin_nhan_nguoi_gui_id");

                    b.HasIndex("NguoiNhanId")
                        .HasDatabaseName("ix_tin_nhan_nguoi_nhan_id");

                    b.ToTable("tin_nhan", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.ViGiaoDich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("loai_giao_dich");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_vi_giao_dich");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("ix_vi_giao_dich_nguoi_dung_id");

                    b.ToTable("vi_giao_dich", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.YeuCauDangKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DiaChiTruSo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi_tru_so");

                    b.Property<string>("EmailLienHe")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_lien_he");

                    b.Property<string>("GiayPhepKinhDoanhUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("giay_phep_kinh_doanh_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_chinh_sua");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_duyet");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiDaiDien")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nguoi_dai_dien");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenDoanhNghiep")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ten_doanh_nghiep");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_yeu_cau_dang_ky");

                    b.ToTable("yeu_cau_dang_ky", (string)null);
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_don_hang_don_hang_don_hang_id");

                    b.HasOne("AgroMarket.Domain.Entities.SanPhamDang", "SanPhamDang")
                        .WithMany()
                        .HasForeignKey("SanPhamDangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_don_hang_san_pham_dang_san_pham_dang_id");

                    b.Navigation("DonHang");

                    b.Navigation("SanPhamDang");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DanhGia", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danh_gia_don_hang_don_hang_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiBiDanhGia")
                        .WithMany()
                        .HasForeignKey("NguoiBiDanhGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_danh_gia_nguoi_dung_nguoi_bi_danh_gia_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiDanhGia")
                        .WithMany()
                        .HasForeignKey("NguoiDanhGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_danh_gia_nguoi_dung_nguoi_danh_gia_id");

                    b.Navigation("DonHang");

                    b.Navigation("NguoiBiDanhGia");

                    b.Navigation("NguoiDanhGia");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DonHang", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiBan")
                        .WithMany("DonHangBan")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_hang_nguoi_dung_nguoi_ban_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiMua")
                        .WithMany("DonHangMua")
                        .HasForeignKey("NguoiMuaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_hang_nguoi_dung_nguoi_mua_id");

                    b.Navigation("NguoiBan");

                    b.Navigation("NguoiMua");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.HoaDonDienTu", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hoa_don_dien_tu_don_hang_don_hang_id");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.HopDongBaoTieu", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "DoanhNghiep")
                        .WithMany()
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hop_dong_bao_tieu_nguoi_dung_doanh_nghiep_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NongDan")
                        .WithMany()
                        .HasForeignKey("NongDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hop_dong_bao_tieu_nguoi_dung_nong_dan_id");

                    b.HasOne("AgroMarket.Domain.Entities.SanPhamDang", "SanPhamDang")
                        .WithMany()
                        .HasForeignKey("SanPhamDangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hop_dong_bao_tieu_san_pham_dang_san_pham_dang_id");

                    b.Navigation("DoanhNghiep");

                    b.Navigation("NongDan");

                    b.Navigation("SanPhamDang");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.LichSuGiaoDich", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lich_su_giao_dich_don_hang_don_hang_id");

                    b.HasOne("AgroMarket.Domain.Entities.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("ThanhToanId")
                        .HasConstraintName("fk_lich_su_giao_dich_thanh_toan_thanh_toan_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("ThucHienBoiId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lich_su_giao_dich_nguoi_dung_thuc_hien_boi_id");

                    b.Navigation("DonHang");

                    b.Navigation("NguoiThucHien");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DanhMuc", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nguoi_dung_danh_muc_vai_tro_id");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.NhatKySanPham", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nhat_ky_san_pham_nguoi_dung_nguoi_thuc_hien_id");

                    b.HasOne("AgroMarket.Domain.Entities.SanPhamDang", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nhat_ky_san_pham_san_pham_dang_san_pham_id");

                    b.Navigation("NguoiThucHien");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.SanPhamChung", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.SanPhamChung", "Cha")
                        .WithMany()
                        .HasForeignKey("ChaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_san_pham_chung_san_pham_chung_cha_id");

                    b.HasOne("AgroMarket.Domain.Entities.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("DanhMucId")
                        .HasConstraintName("fk_san_pham_chung_danh_muc_danh_muc_id");

                    b.HasOne("AgroMarket.Domain.Entities.DanhMuc", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_san_pham_chung_danh_muc_don_vi_id");

                    b.Navigation("Cha");

                    b.Navigation("DanhMuc");

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.SanPhamDang", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DanhMuc", "ChatLuong")
                        .WithMany()
                        .HasForeignKey("ChatLuongId")
                        .HasConstraintName("fk_san_pham_dang_danh_muc_chat_luong_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiBan")
                        .WithMany("CacSanPham")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_san_pham_dang_nguoi_dung_nguoi_ban_id");

                    b.HasOne("AgroMarket.Domain.Entities.SanPhamChung", "SanPhamChung")
                        .WithMany()
                        .HasForeignKey("SanPhamChungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_san_pham_dang_san_pham_chung_san_pham_chung_id");

                    b.Navigation("ChatLuong");

                    b.Navigation("NguoiBan");

                    b.Navigation("SanPhamChung");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.ThanhToan", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.DonHang", "DonHang")
                        .WithMany("CacThanhToan")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_toan_don_hang_don_hang_id");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tin_nhan_nguoi_dung_nguoi_gui_id");

                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tin_nhan_nguoi_dung_nguoi_nhan_id");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.ViGiaoDich", b =>
                {
                    b.HasOne("AgroMarket.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vi_giao_dich_nguoi_dung_nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.DonHang", b =>
                {
                    b.Navigation("CacThanhToan");

                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("AgroMarket.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("CacSanPham");

                    b.Navigation("DonHangBan");

                    b.Navigation("DonHangMua");
                });
#pragma warning restore 612, 618
        }
    }
}
